apiVersion: v1
kind: Pod
metadata:
  name: k8-secrets
  labels:
    topic: secret
    tool: k8
spec:
  containers:
  - name: httpd
    image: httpd:latest
    command: ["httpd", "-DFOREGROUND"]
    envFrom:
    - secretRef:
        name: pod-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    topic: secret
    tool: k8
  ports:
  - protocol: TCP
    port: 80  # service port
    targetPort: 80 # target port
  
      
