apiVersion: v1
kind: Pod
metadata:
  name: k8-secrets
  labels:
    topic: secret
    tool: k8
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
      - name: http   # 🔥 IMPORTANT
        containerPort: 80
    envFrom:
    - secretRef:
        name: pod-secrets
---


apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    topic: secret
    tool: k8
  ports:
  - port: 80
    targetPort: http   # 🔥 use name instead of number